name: Compile Test

on: [push, pull_request]
      
env:
  simba-download: https://github.com/ollydev/Simba/releases/download/autobuild-simba1400/Simba-Win32.exe      
      
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Test
        shell: bash
        run: |
          curl --retry 5 -L -o Simba.exe ${{ env.simba-download }}
          echo "{\$I osr.simba}" > test.simba
          ./Simba.exe --compile test.simba 
          